import {Store} from './store';

export const AlternateFr: Store = {
  currency: '€',
  labels: {
    inStock: {
      container: '#detailPage > div.panel.gray > div.row.main-btn-block > div:nth-child(3) > button > span',
      text: ['Koupit'],
    },
    maxPrice: {
      container: '#detailPage > div.row.panel.price-availability > div:nth-child(2) > div > div.normal',
      euroFormat: false,
    },
  },
  links: [
    {
      brand: 'test:brand',
      model: 'test:model',
      series: 'test:series',
      url: 'https://m.alza.cz/gaming/gigabyte-geforce-rtx-3060-eagle-12g-d6533353.htm',
    },
    {
      brand: 'gainward',
      model: 'ghost',
      series: '3060',
      url: 'https://m.alza.cz/gaming/gainward-geforce-rtx-3060-ghost-12g-d6334304.htm',
    },
    {
      brand: 'gigabyte',
      model: 'vision',
      series: '3060',
      url: 'https://m.alza.cz/gaming/gigabyte-geforce-rtx-3060-vision-oc-12g-d6533356.htm',
    },
    {
      brand: 'gigabyte',
      model: 'eagle',
      series: '3060',
      url: 'https://m.alza.cz/gaming/gigabyte-geforce-rtx-3060-eagle-12g-d6533353.htm',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3060',
      url: 'https://m.alza.cz/gaming/gigabyte-geforce-rtx-3060-eagle-oc-12g-d6533354.htm',
    },
    {
      brand: 'inno3d',
      model: 'twin x2 oc',
      series: '3060',
      url: 'https://m.alza.cz/gaming/inno3d-geforce-rtx-3060-twin-x2-oc-12g-d6330257.htm',
    },
    {
      brand: 'gainward',
      model: 'ghost oc',
      series: '3060',
      url: 'https://m.alza.cz/gaming/gainward-geforce-rtx-3060-ghost-oc-12g-d6334305.htm',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3060',
      url: 'https://m.alza.cz/gaming/msi-geforce-rtx-3060-ventus-3x-12g-oc-d6330249.htm',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3060',
      url: 'https://m.alza.cz/gaming/gigabyte-geforce-rtx-3060-gaming-oc-12g-d6321567.htm',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3060',
      url: 'https://m.alza.cz/gaming/msi-geforce-rtx-3060-gaming-x-trio-12g-d6330246.htm',
    },
    {
      brand: 'gigabyte',
      model: 'aorus elite',
      series: '3060ti',
      url: 'https://m.alza.cz/gaming/gigabyte-aorus-geforce-rtx-3060-elite-12g-d6533352.htm',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3060',
      url: 'https://m.alza.cz/gaming/asus-tuf-geforce-rtx-3060-o12g-gaming-v2-d6533351.htm',
    },
    {
      brand: 'msi',
      model: 'ventus 2x',
      series: '3060',
      url: 'https://m.alza.cz/gaming/msi-geforce-rtx-3060-ventus-2x-12g-oc-d6330248.htm',
    },
    {
      brand: 'inno3d',
      model: 'ichill x3 red',
      series: '3060',
      url: 'https://m.alza.cz/gaming/inno3d-geforce-rtx-3060-ichill-x3-red-12g-d6330255.htm',
    },
    {
      brand: 'msi',
      model: 'gaming x',
      series: '3060',
      url: 'https://m.alza.cz/gaming/msi-geforce-rtx-3060-gaming-x-12g-d6330245.htm',
    },
    {
      brand: 'evga',
      model: 'xc black',
      series: '3060',
      url: 'https://m.alza.cz/gaming/evga-geforce-rtx-3060-xc-black-gaming-d6339055.htm',
    },
    {
      brand: 'palit',
      model: 'stormx oc',
      series: '3060',
      url: 'https://m.alza.cz/gaming/palit-geforce-rtx-3060-stormx-oc-12g-d6334311.htm',
    },
    {
      brand: 'evga',
      model: 'ftw3 ultra',
      series: '3070ti',
      url: 'https://m.alza.cz/evga-geforce-rtx-3070-ti-ftw3-ultra-d6539748.htm',
    },
    {
      brand: 'palit',
      model: 'dual',
      series: '3060',
      url: 'https://m.alza.cz/gaming/palit-geforce-rtx-3060-dual-12g-d6334308.htm',
    },
    {
      brand: 'palit',
      model: 'dual oc',
      series: '3060',
      url: 'https://m.alza.cz/gaming/palit-geforce-rtx-3060-dual-oc-12g-d6334309.htm',
    },
    {
      brand: 'msi',
      model: 'ventus 2x',
      series: '3060',
      url: 'https://m.alza.cz/gaming/msi-geforce-rtx-3060-ventus-2x-12g-d6330247.htm',
    },
    {
      brand: 'inno3d',
      model: 'twin x2',
      series: '3060',
      url: 'https://m.alza.cz/gaming/inno3d-geforce-rtx-3060-twin-x2-12g-d6330256.htm',
    },
    {
      brand: 'gainward',
      model: 'pegasus',
      series: '3060',
      url: 'https://m.alza.cz/gaming/gainward-geforce-rtx-3060-pegasus-12g-d6334306.htm',
    },
    {
      brand: 'evga',
      model: 'xc gaming',
      series: '3060',
      url: 'https://m.alza.cz/gaming/evga-geforce-rtx-3060-xc-gaming-d6339056.htm',
    },
    {
      brand: 'evga',
      model: 'xc lhr',
      series: '3060ti',
      url: 'https://m.alza.cz/evga-geforce-rtx-3060-ti-xc-lhr-d6640442.htm',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3060ti',
      url: 'https://m.alza.cz/gaming/gigabyte-geforce-rtx-3060-ti-gaming-oc-8g-rev-2-0-d6697610.htm',
    },
    {
      brand: 'evga',
      model: 'ftw3 ultra lhr',
      series: '3060ti',
      url: 'https://m.alza.cz/evga-geforce-rtx-3060-ti-ftw3-ultra-lhr-d6640443.htm',
    },
    {
      brand: 'gainward',
      model: 'ghost lhr',
      series: '3060ti',
      url: 'https://m.alza.cz/gaming/gainward-geforce-rtx-3060-ti-ghost-lhr-d6243691.htm',
    },
    {
      brand: 'gigabyte',
      model: 'aorus elite lhr',
      series: '3060ti',
      url: 'https://m.alza.cz/gaming/gigabyte-aorus-geforce-rtx-3060-ti-elite-8g-rev-2-0-d6697607.htm',
    },
    {
      brand: 'msi',
      model: 'gaming x trio lhr',
      series: '3060ti',
      url: 'https://m.alza.cz/gaming/msi-geforce-rtx-3060-ti-gaming-z-trio-8g-lhr-d6541131.htm',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc lhr',
      series: '3060ti',
      url: 'https://m.alza.cz/gaming/gigabyte-geforce-rtx-3060-ti-gaming-oc-pro-8g-rev-3-0-d6697612.htm',
    },
    {
      brand: 'gigabyte',
      model: 'eagle rev2.0 oc',
      series: '3060ti',
      url: 'https://m.alza.cz/gaming/gigabyte-geforce-rtx-3060-ti-eagle-8g-rev-2-0-d6697608.htm',
    },
    {
      brand: 'gigabyte',
      model: 'twin x2',
      series: '3060ti',
      url: 'https://m.alza.cz/gaming/gigabyte-geforce-rtx-3060-ti-eagle-oc-8g-rev-2-0-d6697609.htm',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3060ti',
      url: 'https://m.alza.cz/gaming/gigabyte-geforce-rtx-3060-ti-eagle-oc-8g-d6255496.htm',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc rev2.0',
      series: '3060ti',
      url: 'https://m.alza.cz/gaming/gigabyte-geforce-rtx-3060-ti-vision-oc-8g-rev-2-0-d6697614.htm',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3060ti',
      url: 'https://m.alza.cz/msi-geforce-rtx-3060-ti-ventus-3x-oc-d6270354.htm',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc pro',
      series: '3060ti',
      url: 'https://m.alza.cz/gaming/gigabyte-geforce-rtx-3060-ti-gaming-oc-pro-8g-d6255498.htm',
    },
    {
      brand: 'gainward',
      model: 'phoenix',
      series: '3060ti',
      url: 'https://m.alza.cz/gaming/gainward-geforce-rtx-3060-ti-phoenix-d6243690.htm',
    },
    {
      brand: 'gainward',
      model: 'ghost lhr',
      series: '3060ti',
      url: 'https://m.alza.cz/gaming/gainward-geforce-rtx-3060-ti-ghost-oc-lhr-d6243688.htm',
    },
    {
      brand: 'palit',
      model: 'dual',
      series: '3060ti',
      url: 'https://m.alza.cz/gaming/palit-geforce-rtx-3060-ti-dual-8g-d6276878.htm',
    },
    {
      brand: 'palit',
      model: 'gaming pro',
      series: '3060ti',
      url: 'https://m.alza.cz/gaming/palit-geforce-rtx-3060-ti-gaming-pro-8g-d6276877.htm',
    },
    {
      brand: 'gainward',
      model: 'phoenix gs',
      series: '3060ti',
      url: 'https://m.alza.cz/gaming/gainward-geforce-rtx-3060-ti-phoenix-gs-d6243692.htm',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3060ti',
      url: 'https://m.alza.cz/gigabyte-geforce-rtx-3060-ti-vision-oc-8g-d6329373.htm',
    },
    {
      brand: 'msi',
      model: 'ventus 2xv1 lhr',
      series: '3060ti',
      url: 'https://m.alza.cz/gaming/msi-geforce-rtx-3060-ti-ventus-2x-8g-ocv1-lhr-d6541132.htm',
    },
    {
      brand: 'gigabyte',
      model: 'aorus elite',
      series: '3060ti',
      url: 'https://m.alza.cz/gaming/gigabyte-aorus-geforce-rtx-3060-ti-elite-8g-d6582840.htm',
    },
    {
      brand: 'gigabyte',
      model: 'gaming',
      series: '3060ti',
      url: 'https://m.alza.cz/gaming/gigabyte-geforce-rtx-3060-ti-gaming-8g-d6582841.htm',
    },
    {
      brand: 'evga',
      model: 'xc black lhr',
      series: '3060ti',
      url: 'https://m.alza.cz/evga-geforce-rtx-3060-ti-xc-black-lhr-d6640441.htm',
    },
    {
      brand: 'evga',
      model: 'xc',
      series: '3060ti',
      url: 'https://m.alza.cz/evga-geforce-rtx-3060-ti-xc-d6255522.htm',
    },
    {
      brand: 'evga',
      model: 'ftw3 black',
      series: '3060ti',
      url: 'https://m.alza.cz/evga-geforce-rtx-3060-ti-ftw3-black-d6255523.htm',
    },
    {
      brand: 'evga',
      model: 'ftw3',
      series: '3060ti',
      url: 'https://m.alza.cz/evga-geforce-rtx-3060-ti-ftw3-d6255251.htm',
    },
    {
      brand: 'evga',
      model: 'xc3',
      series: '3080',
      url: 'https://m.alza.cz/gaming/evga-geforce-rtx-3080-xc3-gaming-d6153347.htm',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3080',
      url: 'https://m.alza.cz/gaming/gigabyte-aorus-geforce-rtx-3080-master-10g-d6128463.htm',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3080',
      url: 'https://m.alza.cz/gaming/gigabyte-geforce-rtx-3080-gaming-oc-10g-d6128464.htm',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra hybrid',
      series: '3080',
      url: 'https://m.alza.cz/gaming/evga-geforce-rtx-3080-xc3-ultra-hybrid-gaming-d6292103.htm',
    },
    {
      brand: 'evga',
      model: 'ftw3',
      series: '3080',
      url: 'https://m.alza.cz/gaming/evga-geforce-rtx-3080-ftw3-gaming-d6153346.htm',
    },
    {
      brand: 'msi',
      model: 'suprim x',
      series: '3080',
      url: 'https://m.alza.cz/gaming/msi-geforce-rtx-3080-suprim-x-10g-d6255552.htm',
    },
    {
      brand: 'evga',
      model: 'ftw3 ultra hybrid gaming',
      series: '3080',
      url: 'https://m.alza.cz/gaming/evga-geforce-rtx-3080-ftw3-ultra-hybrid-gaming-d6292104.htm',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3080',
      url: 'https://m.alza.cz/gaming/evga-geforce-rtx-3080-xc3-ultra-gaming-d6153345.htm',
    },
    {
      brand: 'inno3d',
      model: 'twin x2',
      series: '3080',
      url: 'https://m.alza.cz/gaming/inno3d-geforce-rtx-3080-twin-x2-oc-d6286751.htm',
    },
    {
      brand: 'inno3d',
      model: 'ichill x4',
      series: '3080',
      url: 'https://m.alza.cz/gaming/inno3d-geforce-rtx-3080-ichill-x4-d6213824.htm',
    },
    {
      brand: 'evga',
      model: 'xc3 black',
      series: '3080',
      url: 'https://m.alza.cz/gaming/evga-geforce-rtx-3080-xc3-black-gaming-d6153344.htm',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3080',
      url: 'https://m.alza.cz/gaming/msi-geforce-rtx-3080-ventus-3x-10g-oc-d6128457.htm',
    },
    {
      brand: 'msi',
      model: 'ventus 3x',
      series: '3080',
      url: 'https://m.alza.cz/gaming/msi-geforce-rtx-3080-ventus-3x-10g-d6128458.htm',
    },
    {
      brand: 'inno3d',
      model: 'twin x2 oc',
      series: '3080',
      url: 'https://m.alza.cz/gaming/inno3d-geforce-rtx-3080-twin-x2-oc-d6286751.htm',
    },
    {
      brand: 'amd',
      model: 'tripple',
      series: 'rx5700xt',
      url: 'https://m.alza.cz/xfx-radeon-rx-5700-xt-triple-dissipation-8g-d6267840.htm',
    },
    {
      brand: 'gigabyte',
      model: 'gaming',
      series: 'rx5700xt',
      url: 'https://m.alza.cz/gigabyte-radeon-rx-5700-xt-gaming-8g-d5844046.htm',
    },
    {
      brand: 'msi',
      model: 'mech',
      series: 'rx5700xt',
      url: 'https://m.alza.cz/msi-radeon-rx-5700-xt-mech-d5789980.htm',
    },
    {
      brand: 'msi',
      model: 'evoke',
      series: 'rx5700xt',
      url: 'https://m.alza.cz/msi-radeon-rx-5700-xt-evoke-d5789979.htm',
    },
    {
      brand: 'asrock',
      model: 'phantom gaming',
      series: 'rx5700xt',
      url: 'https://m.alza.cz/asrock-radeon-rx-5700-xt-phantom-gaming-d-8g-oc-d5776457.htm',
    },
    {
      brand: 'sapphire',
      model: 'nitro',
      series: 'rx5700xt',
      url: 'https://m.alza.cz/sapphire-radeon-nitro-rx-5700-xt-8g-oc-special-edition-d5734618.htm',
    },
    {
      brand: 'msi',
      model: 'gaming',
      series: 'rx5700xt',
      url: 'https://m.alza.cz/msi-radeon-rx-5700-xt-gaming-8g-d5716019.htm',
    },
    {
      brand: 'amd',
      model: 'ultra',
      series: 'rx5700xt',
      url: 'https://m.alza.cz/xfx-radeon-rx-5700-xt-ultra-8g-d5692192.htm',
    },
    {
      brand: 'sapphire',
      model: 'nitro',
      series: 'rx5700xt',
      url: 'https://m.alza.cz/sapphire-nitro-radeon-rx-5700xt-8g-d5672616.htm',
    },
    {
      brand: 'asrock',
      model: 'challenger',
      series: 'rx5700xt',
      url: 'https://m.alza.cz/asrock-radeon-rx-5700xt-challenger-d-8g-oc-d5669754.htm',
    },
    {
      brand: 'amd',
      model: 'thicc',
      series: 'rx5700xt',
      url: 'https://m.alza.cz/gaming/xfx-radeon-rx-5700-xt-thicc-ii-8gb-d5659484.htm',
    },
    {
      brand: 'asus',
      model: 'gaming',
      series: 'rx5700xt',
      url: 'https://m.alza.cz/asus-tuf3-gaming-radeon-rx-5700-xt-o8g-d5659163.htm',
    },
    {
      brand: 'msi',
      model: 'mech',
      series: 'rx5700xt',
      url: 'https://m.alza.cz/gaming/msi-radeon-rx-5700-xt-mech-oc-d5656360.htm',
    },
    {
      brand: 'sapphire',
      model: 'pulse',
      series: 'rx5700xt',
      url: 'https://m.alza.cz/sapphire-pulse-radeon-rx-5700xt-8g-d5656000.htm',
    },
    {
      brand: 'msi',
      model: 'mech',
      series: 'rx6700xt',
      url: 'https://m.alza.cz/msi-radeon-rx-6700-xt-mech-2x-12g-oc-d6369316.htm',
    },
    {
      brand: 'msi',
      model: 'radeon',
      series: 'rx6700xt',
      url: 'https://m.alza.cz/msi-amd-radeon-rx-6700-xt-12g-d6369312.htm',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: 'rx6700xt',
      url: 'https://www.alza.cz/gigabyte-radeon-rx-6700-xt-gaming-oc-12g-d6369319.htm',
    },
    {
      brand: 'gigabyte',
      model: 'aorus elite',
      series: 'rx6700xt',
      url: 'https://m.alza.cz/gigabyte-aorus-radeon-rx-6700-xt-elite-12g-d6563661.htm',
    },
    {
      brand: 'sapphire',
      model: 'pulse',
      series: 'rx6700xt',
      url: 'https://m.alza.cz/sapphire-pulse-radeon-rx-6700-xt-16g-d6386172.htm',
    },
    {
      brand: 'sapphire',
      model: 'nitro',
      series: 'rx6700xt',
      url: 'https://m.alza.cz/sapphire-nitro-radeon-rx-6700-xt-12g-d6386171.htm',
    },
    {
      brand: 'asrock',
      model: 'phantom gaming',
      series: 'rx6700xt',
      url: 'https://m.alza.cz/sapphire-nitro-radeon-rx-6700-xt-12g-d6386171.htm',
    },
    {
      brand: 'asrock',
      model: 'challenger pro',
      series: 'rx6700xt',
      url: 'https://m.alza.cz/asrock-radeon-rx-6700-xt-challenger-pro-12gb-oc-d6527881.htm',
    },
    {
      brand: 'asrock',
      model: 'challenger',
      series: 'rx6700xt',
      url: 'https://m.alza.cz/asrock-radeon-rx-6700-xt-challenger-pro-12gb-oc-d6527881.htm',
    },
    {
      brand: 'msi',
      model: 'mech',
      series: 'rx6700xt',
      url: 'https://m.alza.cz/msi-radeon-rx-6700-xt-mech-2x-12g-d6369315.htm',
    },
    {
      brand: 'msi',
      model: 'gaming x',
      series: 'rx6700xt',
      url: 'https://m.alza.cz/msi-radeon-rx-6700-xt-gaming-x-12g-d6369314.htm',
    },
    {
      brand: 'msi',
      model: 'gaming',
      series: 'rx6700xt',
      url: 'https://www.alza.cz/msi-radeon-rx-6700-xt-gaming-12g-d6369313.htm',
    },
  ],
  name: 'alza',
};
